ingress:
  enabled: true
  className: nginx
  host: homelab.local

backend:
  image:
    repository: homelab-api
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  environment: kubernetes
  servicePort: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  image:
    repository: homelab-frontend
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  servicePort: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
